// generated by stringer -type=TokenType; DO NOT EDIT

package vblexer

import "fmt"

const _TokenType_name = "EOFSTATEMENTFUNCTIONKEYWORDKEYWORD_BOOLCOLOR_CONSTANTCOMPARE_CONSTANTDATE_CONSTANTDATEFORMAT_CONSTANTMISC_CONSTANTMSGBOX_CONSTANTSTRING_CONSTANTTRISTATE_CONSTANTVARTYPE_CONSTANTIDENTIFIERSTRINGINTFLOATDATECOMMENTHTMLCHAREOLOPCONTINUATION"

var _TokenType_index = [...]uint8{0, 3, 12, 20, 27, 39, 53, 69, 82, 101, 114, 129, 144, 161, 177, 187, 193, 196, 201, 205, 212, 216, 220, 223, 225, 237}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
