// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package vblexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[STATEMENT-1]
	_ = x[FUNCTION-2]
	_ = x[KEYWORD-3]
	_ = x[KEYWORD_BOOL-4]
	_ = x[COLOR_CONSTANT-5]
	_ = x[COMPARE_CONSTANT-6]
	_ = x[DATE_CONSTANT-7]
	_ = x[DATEFORMAT_CONSTANT-8]
	_ = x[MISC_CONSTANT-9]
	_ = x[MSGBOX_CONSTANT-10]
	_ = x[STRING_CONSTANT-11]
	_ = x[TRISTATE_CONSTANT-12]
	_ = x[VARTYPE_CONSTANT-13]
	_ = x[IDENTIFIER-14]
	_ = x[STRING-15]
	_ = x[INT-16]
	_ = x[FLOAT-17]
	_ = x[DATE-18]
	_ = x[COMMENT-19]
	_ = x[HTML-20]
	_ = x[CHAR-21]
	_ = x[EOL-22]
	_ = x[OP-23]
	_ = x[CONTINUATION-24]
	_ = x[FILE_INCLUDE-25]
	_ = x[VIRTUAL_INCLUDE-26]
	_ = x[LIST_SEP-27]
	_ = x[PAREN_OPEN-28]
	_ = x[PAREN_CLOSE-29]
	_ = x[FIELD_SEP-30]
}

const _TokenType_name = "EOFSTATEMENTFUNCTIONKEYWORDKEYWORD_BOOLCOLOR_CONSTANTCOMPARE_CONSTANTDATE_CONSTANTDATEFORMAT_CONSTANTMISC_CONSTANTMSGBOX_CONSTANTSTRING_CONSTANTTRISTATE_CONSTANTVARTYPE_CONSTANTIDENTIFIERSTRINGINTFLOATDATECOMMENTHTMLCHAREOLOPCONTINUATIONFILE_INCLUDEVIRTUAL_INCLUDELIST_SEPPAREN_OPENPAREN_CLOSEFIELD_SEP"

var _TokenType_index = [...]uint16{0, 3, 12, 20, 27, 39, 53, 69, 82, 101, 114, 129, 144, 161, 177, 187, 193, 196, 201, 205, 212, 216, 220, 223, 225, 237, 249, 264, 272, 282, 293, 302}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
