// generated by stringer -type=TokenType; DO NOT EDIT

package vbscanner

import "fmt"

const _TokenType_name = "EOFEOLIdentStringIntegerFloatDateCommentHtmlCharOp"

var _TokenType_index = [...]uint8{0, 3, 6, 11, 17, 24, 29, 33, 40, 44, 48, 50}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
